import type { ITree } from '~/types/tree'

/** Каталог деревьев с ценами */
export const TREES: ITree[] = [
  {
    id: 'oak',
    name: 'Дуб черешчатый',
    latinName: 'Quercus robur',
    price: 1500,
    co2PerYear: 22,
    lifespan: 500,
    description: 'Мощное листопадное дерево с высокой способностью поглощения CO₂. Идеален для долгосрочных карбоновых проектов.',
    badge: 'Популярный',
  },
  {
    id: 'pine',
    name: 'Сосна обыкновенная',
    latinName: 'Pinus sylvestris',
    price: 800,
    co2PerYear: 18,
    lifespan: 300,
    description: 'Хвойное дерево с круглогодичной фотосинтетической активностью. Быстро растёт, неприхотливо к почве.',
    badge: null,
  },
  {
    id: 'birch',
    name: 'Берёза повислая',
    latinName: 'Betula pendula',
    price: 600,
    co2PerYear: 12,
    lifespan: 150,
    description: 'Быстрорастущее дерево, хорошо адаптированное к российскому климату. Отличный выбор для быстрого озеленения.',
    badge: null,
  },
  {
    id: 'spruce',
    name: 'Ель обыкновенная',
    latinName: 'Picea abies',
    price: 900,
    co2PerYear: 16,
    lifespan: 250,
    description: 'Вечнозелёное хвойное дерево с высокой плотностью кроны. Эффективно поглощает углерод в течение всего года.',
    badge: null,
  },
  {
    id: 'larch',
    name: 'Лиственница сибирская',
    latinName: 'Larix sibirica',
    price: 1200,
    co2PerYear: 20,
    lifespan: 400,
    description: 'Морозостойкое хвойное дерево с высокой долговечностью. Особенно эффективно в суровых климатических условиях.',
    badge: 'Премиум',
  },
  {
    id: 'maple',
    name: 'Клён остролистный',
    latinName: 'Acer platanoides',
    price: 1100,
    co2PerYear: 15,
    lifespan: 200,
    description: 'Декоративное лиственное дерево с широкой кроной. Подходит для городских карбоновых ферм и парковых зон.',
    badge: null,
  },
]